<script src="<?= base_url('assets/template/plugins/jquery/jquery.min.js'); ?>"></script>
<script src="<?= base_url('assets/template/plugins/jquery-ui/jquery-ui.min.js'); ?>"></script>
<script src="<?= base_url('assets/template/plugins/bootstrap/js/bootstrap.bundle.min.js'); ?>"></script>
<script src="<?= base_url('assets/template/plugins/chart.js/Chart.min.js'); ?>"></script>
<script src="<?= base_url('assets/template/plugins/sparklines/sparkline.js'); ?>"></script>
<script src="<?= base_url('assets/template/plugins/jquery-knob/jquery.knob.min.js'); ?>"></script>
<script src="<?= base_url('assets/template/plugins/moment/moment.min.js'); ?>"></script>
<script src="<?= base_url('assets/template/plugins/daterangepicker/daterangepicker.js'); ?>"></script>
<script src="<?= base_url('assets/template/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js'); ?>"></script>
<script src="<?= base_url('assets/template/plugins/summernote/summernote-bs4.min.js'); ?>"></script>
<script src="<?= base_url('assets/template/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js'); ?>"></script>
<script src="<?= base_url('assets/template/dist/js/adminlte.js'); ?>"></script>
<script src="<?= base_url('assets/template/dist/js/pages/dashboard.js'); ?>"></script>
